version: "3"
services:
    ranking-database:
        container_name: rankingDatabase
        image: postgres:10
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
        command: -c "listen_addresses=*"
        ports:
            - "5432:5432"
